name: CD Pipeline-1

#on:
#  pull_request:
#    types: [closed]
#  push:
#    branches:
#      - main

on: [ push ]

jobs:
  deploy:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v4
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
