name: CD Pipeline-1

#on:
#  pull_request:
#    types: [closed]
#  push:
#    branches:
#      - main

#on push only for testing
on: [ push ]

jobs:
  deploy:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary

      - name: Install Render CLI
        run: |
          curl -LO https://github.com/render-oss/render-cli/releases/download/v0.1.11/render-linux-x86_64
          chmod +x render-linux-x86_64
          sudo mv render-linux-x86_64 /usr/local/bin/render

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.MY_RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.MY_RENDER_SERVICE_ID }}
        run: |
          render services update $MY_RENDER_SERVICE_ID --branch main --env production
