name: CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary

      - name: Run tests
        run: |
          python manage.py migrate
          python manage.py test

      - name: Collect Test Coverage
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report

      - name: Linting
        run: |
          pip install flake8
          flake8 --config .flake8

      - name: Security checks
        run: |
          pip install bandit
          bandit -r .
