name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          cd test_project_38_setup &&
          git pull origin main &&
          sudo pip3 install -r requirements.txt &&
          python3 manage.py migrate &&
          python3 manage.py collectstatic --noinput &&
          sudo systemctl restart gunicorn_test_project_38_setup &&
          sudo systemctl restart nginx
        '