name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-3'  # Replace with your AWS region
          AWS_EB_APPLICATION_NAME: 'project_38_georgi'  # Replace with your EB application name
          AWS_EB_ENVIRONMENT_NAME: 'your-environment-name'  # Replace with your EB environment name
        run: |
          eb init -p python-3.x your-application-name --region $AWS_REGION
          eb deploy $AWS_EB_ENVIRONMENT_NAME
