name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
#        python manage.py collectstatic --noinput

  run-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
#        python manage.py collectstatic --noinput

    - name: Run Tests
      run: |
        python manage.py test

    - name: Collect Test Coverage
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report

  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v4
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
#          wait_deploy: true